# 101 Numpy Exercises for Data Analysis

## 1. Import numpy as np and see the version?

In [1]:
import numpy as np
print(np.__version__)

1.14.1


## 2. How to create a 1D array?

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array?

In [3]:
truearr = np.full((3,3), True, dtype=bool)
truearr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# Or
truearr1 = np.ones((3,3), dtype=bool)
truearr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. How to extract items that satify a given condition from 1D array?

Q. Extract all odd number from `arr`

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a contition with another value in numpy array?

Q. Replace all add number in `arr` with -1

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a condition without affecting the original array?

Q. Replace all odd numbers in `arr` with -1 without changing `arr`

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
newarr = arr.copy()
newarr[newarr % 2 == 1] = -1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
newarr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
# Another solution
newarr = np.where(arr % 2 == 1, -1, arr)
print(arr)
newarr

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 7. How to reshape an array?

Q. Convert a 1D array to a 2D arrray with 2 rows

In [19]:
arr = np.arange(10)
newarr = arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols
print(arr)
newarr

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. How to stack two arrays vertically?

Q. Stack arrays `a` and `b` vertically

In [20]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

In [24]:
# Method 1
c1 = np.concatenate([a, b], axis=0)

# Method 2
c2 = np.vstack([a, b])

# Method 3
c3 = np.r_[a, b]

print(c1)
print("________________________")
print(c2)
print("________________________")
print(c3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
________________________
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
________________________
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. How to stack two arrays horizontially?

Q. Stack two arrays `a` and `b` horizontally.

In [23]:
# Method 1
d1 = np.concatenate([a,b], axis=1)

# Method 2
d2 = np.hstack([a, b])

# Method 3
d3 = np.c_[a, b]

print(d1)
print("________________________")
print(d2)
print("________________________")
print(d3)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
________________________
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
________________________
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. How to generate custom sequences in numpy without hardcoding?

Q. Create the following pattern without hardcoding.

In [25]:
a = np.array([1, 2, 3])

In [28]:
b = np.r_[np.repeat(a, 3), np.tile(a, 3)]
b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. How to get the common items between two python numpy arrays?

Q. Get the common items between `a` and `b`

In [29]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [30]:
c = np.intersect1d(a, b)
c

array([2, 4])

## 12. How to remove from one array those items that exist in another?

Q. From array `a` remove all items present in array `b`

In [31]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [34]:
c = np.setdiff1d(a, b)
c

array([1, 2, 3, 4])

## 13. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of `a` and `b` match

In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [36]:
c = np.where(a == b)
c

(array([1, 3, 5, 7]),)

## 14. How to extract all numbers between a given range from a numpy array?

Q. Get all items between 5 and 10 from `a`

In [37]:
a = np.arange(15)

In [38]:
# Method 1
b1 = a[np.where((a >= 5) & (a <= 10))]

# Method 2
b2 = a[np.where(np.logical_and(a>=5, a<=10))]

# Method 3
b3 = a[(a >= 5) & (a <= 10)]

print(b1)
print("________________")
print(b2)
print("________________")
print(b3)

[ 5  6  7  8  9 10]
________________
[ 5  6  7  8  9 10]
________________
[ 5  6  7  8  9 10]


## 15. How to make a python function that handles scalears to work on numpy arrays?

Q. Convert the functions `maxx` that works on two scalars, to work on two arrays.

In [42]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [43]:
pair_max = np.vectorize(maxx, otypes=[float])    

In [45]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

## 16. How to swap two columns in a 2d numpy array?

Q. Swap columns 1 and 2 in the array `arr`

In [46]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. How to swap two rows in a 2d numpy array?

Q. Swap rows 1 and 2 in the array `arr`

In [48]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## 18. How to reverse the rows of a 2d array?

In [50]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 19. How to reverse the columns fi a 2D array?

In [53]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 20. How to create a 2D array containing random floats between 5 and 10?

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10?

In [56]:
# Method 1
rand_arr1 = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr1)

# Method 2
rand_arr2 = np.random.uniform(5, 10, size=(5,3))
print(rand_arr2)

[[7.18558345 5.08314079 8.2673105 ]
 [5.58791856 8.87941113 5.76710102]
 [6.70013154 7.80832487 6.23394005]
 [6.33456451 7.78563308 8.05178305]
 [9.87616611 8.95929216 8.70619568]]
[[7.72967562 5.77884805 7.01028955]
 [7.64762562 8.92243352 7.97437999]
 [8.95713966 9.90258738 9.76348359]
 [6.07030789 6.77742853 6.4017111 ]
 [5.5738506  9.13166995 6.37706796]]


## 21. How to print only 3 decimal places in python numpy array?

Q. Print or show only 3 decimal places of the numpy array `rand_arr`

In [57]:
rand_arr = np.random.random((5,3))

In [58]:
rand_arr

array([[0.8281678 , 0.70705545, 0.50126995],
       [0.91502526, 0.16470956, 0.8472069 ],
       [0.4841812 , 0.29113874, 0.91349011],
       [0.5444696 , 0.3728686 , 0.65956167],
       [0.2805395 , 0.89329058, 0.98449584]])

In [59]:
np.set_printoptions(precision=3)

In [60]:
rand_arr

array([[0.828, 0.707, 0.501],
       [0.915, 0.165, 0.847],
       [0.484, 0.291, 0.913],
       [0.544, 0.373, 0.66 ],
       [0.281, 0.893, 0.984]])

## 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

Q. Pretty print `rand_arr` by suppressing the scientific notation

In [62]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [63]:
# Reset printoptions to default
np.set_printoptions(suppress=False)
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [64]:
# Enable suppressing
np.set_printoptions(suppress=True, precision=6) # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

## 23. How to limit the number of items printed in output of numpy array?

In [65]:
a = np.arange(15)

In [66]:
# LImit number of items printed to 6
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

## 24. Hot to print the full numpy array without truncating

In [67]:
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. How to import a dataset with numbers and texts keeping the text intact?

Q. Import the [irris dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) keeping the text intact.

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris.shape

(150, 5)

In [70]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

## 26. How to extract a particular column from 1D array of tubles?

Q. Extract the text column `species` from iris data.

In [71]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

(150,)


/Users/trang/anaconda/envs/jupyterlab/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [75]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

## 27. How to convert a 1D array of tuples to 2D numpy array?

Q. Convert the 1D iris to 2D array by omitting the speciese text field.

In [77]:
# Method 1
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [78]:
# Method 2
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

## 28. How to compute the mean, median, standard deviation of a numpy array?

Q. Find the mean, median, standard deviation of iris's sepallenth

In [79]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [80]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


## 29. How to normalize an array so the values range exactly between 0 and 1.

Q. Normalize the iris's sepallength

In [82]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [83]:
# Or
S1 = (sepallength - Smin)/sepallength.ptp()
print(S1)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

## 30. How to compute the softmax score?

Q. Compute the softmax score of sepallength

In [87]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [88]:
print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

## 31. How to find the percentile scores of a numpy array?

Q. Find the 5th and 95th percentile of iris's sepallength.

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [3]:
np.percentile(sepallength, q = [5, 95])

array([4.6  , 7.255])

## 32. How to insert values at random positions in an array?

Q. Insert `np.nan` values at 20 random positions in `iris_2d` dataset

In [17]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [15]:
# Method 1
i, j = np.where(iris_2d)

# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan
print(iris_2d[:20])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' nan b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' nan b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' nan b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']]


In [18]:
# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


## 33. How to find the position of missing values in numpy array?

Q. Find the number and position of missing values in iris's sepallength.

In [19]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [24]:
print("Number of missing values: ", np.isnan(iris_2d[:,0]).sum())
print("Position of missing values: ", np.where(np.isnan(iris_2d[:,0])))

Number of missing values:  5
Position of missing values:  (array([ 38,  80, 106, 113, 121]),)


## 34. How to filter a numpy array based on two or more conditions?

Filter the rows of iriss that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [35]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [36]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:,0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## 35. How to drop rows that contain a missing values from a numpy array?

Q. Select the rows of iris that does not have any nan value.

In [38]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [40]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

In [41]:
# Or
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])